# Generated by Django 6.0.5 on 2026-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(help_text="Role name (e.g. 'admin', 'user', 'developer') or User Email (e.g. 'user@company.com')", max_length=255, unique=True)),
                ('allowed_models', models.TextField(help_text="Comma-separated list of allowed models (e.g. 'qwen3.5:2b,gpt-4o')")),
            ],
        ),
    ]
