# Generated by Django 6.0.5 on 2026-06-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the model used by Open WebUI (es. 'qwen3.5:2b')", max_length=100, unique=True)),
                ('agent_url', models.CharField(help_text="Complete associated langserve agent's URL (es. 'http://agent-qwen-2b:8001/agent/')", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Able or disable this model at runtime')),
            ],
        ),
    ]
