# Generated by Django 6.0.5 on 2026-05-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome del modello utilizzato da Open WebUI (es. 'qwen3.5:2b')", max_length=100, unique=True)),
                ('agent_url', models.URLField(help_text="URL completo dell'agent Langserve associato (es. 'http://agent-qwen-2b:8001/agent/')", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Abilita o disabilita questo modello a runtime')),
            ],
        ),
    ]
