# Generated by Django 6.0.5 on 2026-05-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_seed_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='agent_url',
            field=models.CharField(help_text="Complete associated langserve agent's URL (es. 'http://agent-qwen-2b:8001/agent/')", max_length=500),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Able or disable this model at runtime'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(help_text="Name of the model used by Open WebUI (es. 'qwen3.5:2b')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='modelpermission',
            name='allowed_models',
            field=models.TextField(help_text="List of allowed models (e.g. 'qwen3.5:2b,gpt-4o')"),
        ),
        migrations.AlterField(
            model_name='modelpermission',
            name='identity',
            field=models.CharField(help_text="Role name (es. 'admin', 'user') or user email (es. 'user@company.com')", max_length=255, unique=True),
        ),
    ]
